branches:
  except:
    - gh-pages
language: perl
perl:
  - "5.22"
  - "5.20"
  - "5.18"  # IO::Tty is missing on the Travis server or cannot be installed?
  - "5.16"
  - "5.14"
  - "5.12"
  - "5.10"
notifications:
  email: false
  irc:
    channels:
      - "irc.perl.org#purduepm"
    template:
      - "%{result}: %{repository} (%{commit}) %{commit_subject}"
    on_success: change
    on_failure: always
    use_notice: true
