branches:
  except:
    - gh-pages
language: perl
before_install:
  - cpanm JSON
  - cpanm Net::OpenSSH 
os:
  - linux
  - osx
perl:
  - "5.26"
  - "5.24"
  - "5.22"
  - "5.20"
  - "5.18"  # IO::Tty is missing on the Travis server or cannot be installed?
  - "5.16"
  - "5.14"
  - "5.12"
  - "5.10"
sudo: false             # faster builds as long as you don't need sudo access

matrix:
  include:
    - perl: 5.18
      env: COVERAGE=1   # enables coverage+coveralls reporting
  allow_failures:
    - perl: blead       # ignore failures for blead perl
sudo: false             # faster builds as long as you don't need sudo access
before_install:
  - eval $(curl https://travis-perl.github.io/init) --auto

notifications:
  email:
    - jacoby@cpan.org
  on_success: change
  on_failure: always 


